# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/fpga_study/ARM/cortex_m3_on_xc7a100t/bd/cm3_core/ip/cm3_core_axi_gpio_0_1/cm3_core_axi_gpio_0_1.xci
# IP: The module: 'cm3_core_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/fpga_study/ARM/cortex_m3_on_xc7a100t/bd/cm3_core/ip/cm3_core_axi_gpio_0_1/cm3_core_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cm3_core_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/fpga_study/ARM/cortex_m3_on_xc7a100t/bd/cm3_core/ip/cm3_core_axi_gpio_0_1/cm3_core_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cm3_core_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/fpga_study/ARM/cortex_m3_on_xc7a100t/bd/cm3_core/ip/cm3_core_axi_gpio_0_1/cm3_core_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'cm3_core_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/fpga_study/ARM/cortex_m3_on_xc7a100t/bd/cm3_core/ip/cm3_core_axi_gpio_0_1/cm3_core_axi_gpio_0_1.xci
# IP: The module: 'cm3_core_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/fpga_study/ARM/cortex_m3_on_xc7a100t/bd/cm3_core/ip/cm3_core_axi_gpio_0_1/cm3_core_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cm3_core_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/fpga_study/ARM/cortex_m3_on_xc7a100t/bd/cm3_core/ip/cm3_core_axi_gpio_0_1/cm3_core_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cm3_core_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/fpga_study/ARM/cortex_m3_on_xc7a100t/bd/cm3_core/ip/cm3_core_axi_gpio_0_1/cm3_core_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'cm3_core_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
