# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/fpga_study/ARM/cortex_m3_on_xc7a100t/xdc/top_hdl.xdc

# Block Designs: D:/fpga_study/ARM/cortex_m3_on_xc7a100t/bd/cm3_core/cm3_core.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cm3_core || ORIG_REF_NAME==cm3_core} -quiet] -quiet

# IP: D:/fpga_study/ARM/cortex_m3_on_xc7a100t/bd/cm3_core/ip/cm3_core_CORTEXM3_AXI_0_0/cm3_core_CORTEXM3_AXI_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cm3_core_CORTEXM3_AXI_0_0 || ORIG_REF_NAME==cm3_core_CORTEXM3_AXI_0_0} -quiet] -quiet

# IP: D:/fpga_study/ARM/cortex_m3_on_xc7a100t/bd/cm3_core/ip/cm3_core_clk_wiz_0_0/cm3_core_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cm3_core_clk_wiz_0_0 || ORIG_REF_NAME==cm3_core_clk_wiz_0_0} -quiet] -quiet

# IP: D:/fpga_study/ARM/cortex_m3_on_xc7a100t/bd/cm3_core/ip/cm3_core_proc_sys_reset_0_0/cm3_core_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cm3_core_proc_sys_reset_0_0 || ORIG_REF_NAME==cm3_core_proc_sys_reset_0_0} -quiet] -quiet

# IP: D:/fpga_study/ARM/cortex_m3_on_xc7a100t/bd/cm3_core/ip/cm3_core_xbar_0/cm3_core_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cm3_core_xbar_0 || ORIG_REF_NAME==cm3_core_xbar_0} -quiet] -quiet

# IP: D:/fpga_study/ARM/cortex_m3_on_xc7a100t/bd/cm3_core/ip/cm3_core_axi_interconnect_0_0/cm3_core_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cm3_core_axi_interconnect_0_0 || ORIG_REF_NAME==cm3_core_axi_interconnect_0_0} -quiet] -quiet

# IP: D:/fpga_study/ARM/cortex_m3_on_xc7a100t/bd/cm3_core/ip/cm3_core_util_vector_logic_0_0/cm3_core_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cm3_core_util_vector_logic_0_0 || ORIG_REF_NAME==cm3_core_util_vector_logic_0_0} -quiet] -quiet

# IP: D:/fpga_study/ARM/cortex_m3_on_xc7a100t/bd/cm3_core/ip/cm3_core_xlconstant_0_0/cm3_core_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cm3_core_xlconstant_0_0 || ORIG_REF_NAME==cm3_core_xlconstant_0_0} -quiet] -quiet

# IP: D:/fpga_study/ARM/cortex_m3_on_xc7a100t/bd/cm3_core/ip/cm3_core_xlconstant_0_1/cm3_core_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cm3_core_xlconstant_0_1 || ORIG_REF_NAME==cm3_core_xlconstant_0_1} -quiet] -quiet

# IP: D:/fpga_study/ARM/cortex_m3_on_xc7a100t/bd/cm3_core/ip/cm3_core_xlconstant_1_0/cm3_core_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cm3_core_xlconstant_1_0 || ORIG_REF_NAME==cm3_core_xlconstant_1_0} -quiet] -quiet

# IP: D:/fpga_study/ARM/cortex_m3_on_xc7a100t/bd/cm3_core/ip/cm3_core_axi_gpio_0_1/cm3_core_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cm3_core_axi_gpio_0_1 || ORIG_REF_NAME==cm3_core_axi_gpio_0_1} -quiet] -quiet

# IP: D:/fpga_study/ARM/cortex_m3_on_xc7a100t/bd/cm3_core/ip/cm3_core_axi_uartlite_0_0/cm3_core_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cm3_core_axi_uartlite_0_0 || ORIG_REF_NAME==cm3_core_axi_uartlite_0_0} -quiet] -quiet

# IP: D:/fpga_study/ARM/cortex_m3_on_xc7a100t/bd/cm3_core/ip/cm3_core_swdio_tri_buffer_0_0/cm3_core_swdio_tri_buffer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cm3_core_swdio_tri_buffer_0_0 || ORIG_REF_NAME==cm3_core_swdio_tri_buffer_0_0} -quiet] -quiet

# IP: d:/fpga_study/ARM/cortex_m3_on_xc7a100t/bd/cm3_core/ip/cm3_core_auto_pc_0/cm3_core_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cm3_core_auto_pc_0 || ORIG_REF_NAME==cm3_core_auto_pc_0} -quiet] -quiet

# XDC: D:/fpga_study/ARM/cortex_m3_on_xc7a100t/bd/cm3_core/cm3_core_ooc.xdc
