# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/fpga_study/ARM/cortex_m3_on_xc7a100t/bd/cm3_core/ip/cm3_core_CORTEXM3_AXI_0_0/cm3_core_CORTEXM3_AXI_0_0.xci
# IP: The module: 'cm3_core_CORTEXM3_AXI_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/fpga_study/ARM/cortex_m3_on_xc7a100t/bd/cm3_core/ip/cm3_core_CORTEXM3_AXI_0_0/cm3_core_CORTEXM3_AXI_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'cm3_core_CORTEXM3_AXI_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/fpga_study/ARM/cortex_m3_on_xc7a100t/bd/cm3_core/ip/cm3_core_CORTEXM3_AXI_0_0/cm3_core_CORTEXM3_AXI_0_0.xci
# IP: The module: 'cm3_core_CORTEXM3_AXI_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/fpga_study/ARM/cortex_m3_on_xc7a100t/bd/cm3_core/ip/cm3_core_CORTEXM3_AXI_0_0/cm3_core_CORTEXM3_AXI_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'cm3_core_CORTEXM3_AXI_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
